name: Create Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          VERSION=$(echo $TAG_NAME | sed 's/^v//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Patch manifest and create zip
        run: |
          sed -i 's/"0.0.0"/"${{ env.VERSION }}"/' custom_components/renfrew_bridge/manifest.json
          cd custom_components/renfrew_bridge/
          zip -r ../../renfrew_bridge.zip ./* -x '.*'

      - name: Upload Release Asset
        uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./renfrew_bridge.zip application/zip
