name: Create Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: Patch manifest and create zip
        run: |
          sed -i 's/0.0.0/${{ steps.version.outputs.version }}/' custom_components/renfrew_bridge/manifest.json
          cd custom_components/renfrew_bridge/
          zip -r ../../renfrew_bridge.zip ./* -x '.*'

      - name: Upload Release Asset
        uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./renfrew_bridge.zip application/zip
